const express=require('express'); 
const router=express.Router(); 
const userController=require('../controllers/controller.js'); 
const validate=require('../../middleware/validate.js');
const CompleteUserSchema= require('../../../validators/register_validator.js');
router.get('/users',userController.getAllUsers);
router.get('/users/:id',userController.getUserById);
//router.post('/users',userController.createUser);
router.put('/users/:id',userController.updateUser);
router.delete('/users/:id',userController.deleteUser);
router.post('/users',validate(CompleteUserSchema),userController.createUser);
router.patch('/users/:id',userController.PartialUpdateUser);
module.exports=router;
